
const tabelaPeriodicaDados = {
  "metadata": {
    "system": "Tabela Periódica Científica Profissional",
    "version": "IUPAC 2026",
    "developer": "EDCELLTECH"
  },
  "elements": [
    
    { "atomicNumber": 1, "symbol": "H", "namePt": "Hidrogênio", "atomicMass": 1.008, "category": "Não Metais", "group": 1, "period": 1, "block": "s", "state": "Gasoso", "electronConfigurationShort": "1s¹", "shells": [1] },
    { "atomicNumber": 2, "symbol": "He", "namePt": "Hélio", "atomicMass": 4.0026, "category": "Gases Nobres", "group": 18, "period": 1, "block": "s", "state": "Gasoso", "electronConfigurationShort": "1s²", "shells": [2] },

 
    { "atomicNumber": 3, "symbol": "Li", "namePt": "Lítio", "atomicMass": 6.94, "category": "Metais Alcalinos", "group": 1, "period": 2, "block": "s", "state": "Sólido", "electronConfigurationShort": "[He] 2s¹", "shells": [2, 1] },
    { "atomicNumber": 4, "symbol": "Be", "namePt": "Berílio", "atomicMass": 9.0122, "category": "Metais Alcalino-Terrosos", "group": 2, "period": 2, "block": "s", "state": "Sólido", "electronConfigurationShort": "[He] 2s²", "shells": [2, 2] },
    { "atomicNumber": 5, "symbol": "B", "namePt": "Boro", "atomicMass": 10.81, "category": "Semimetais", "group": 13, "period": 2, "block": "p", "state": "Sólido", "electronConfigurationShort": "[He] 2s² 2p¹", "shells": [2, 3] },
    { "atomicNumber": 6, "symbol": "C", "namePt": "Carbono", "atomicMass": 12.011, "category": "Não Metais", "group": 14, "period": 2, "block": "p", "state": "Sólido", "electronConfigurationShort": "[He] 2s² 2p²", "shells": [2, 4] },
    { "atomicNumber": 7, "symbol": "N", "namePt": "Nitrogênio", "atomicMass": 14.007, "category": "Não Metais", "group": 15, "period": 2, "block": "p", "state": "Gasoso", "electronConfigurationShort": "[He] 2s² 2p³", "shells": [2, 5] },
    { "atomicNumber": 8, "symbol": "O", "namePt": "Oxigênio", "atomicMass": 15.999, "category": "Não Metais", "group": 16, "period": 2, "block": "p", "state": "Gasoso", "electronConfigurationShort": "[He] 2s² 2p⁴", "shells": [2, 6] },
    { "atomicNumber": 9, "symbol": "F", "namePt": "Flúor", "atomicMass": 18.998, "category": "Halogênios", "group": 17, "period": 2, "block": "p", "state": "Gasoso", "electronConfigurationShort": "[He] 2s² 2p⁵", "shells": [2, 7] },
    { "atomicNumber": 10, "symbol": "Ne", "namePt": "Neônio", "atomicMass": 20.180, "category": "Gases Nobres", "group": 18, "period": 2, "block": "p", "state": "Gasoso", "electronConfigurationShort": "[He] 2s² 2p⁶", "shells": [2, 8] },


    { "atomicNumber": 11, "symbol": "Na", "namePt": "Sódio", "atomicMass": 22.990, "category": "Metais Alcalinos", "group": 1, "period": 3, "block": "s", "state": "Sólido", "electronConfigurationShort": "[Ne] 3s¹", "shells": [2, 8, 1] },
    { "atomicNumber": 12, "symbol": "Mg", "namePt": "Magnésio", "atomicMass": 24.305, "category": "Metais Alcalino-Terrosos", "group": 2, "period": 3, "block": "s", "state": "Sólido", "electronConfigurationShort": "[Ne] 3s²", "shells": [2, 8, 2] },
    { "atomicNumber": 13, "symbol": "Al", "namePt": "Alumínio", "atomicMass": 26.982, "category": "Metais Pós-Transição", "group": 13, "period": 3, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Ne] 3s² 3p¹", "shells": [2, 8, 3] },
    { "atomicNumber": 14, "symbol": "Si", "namePt": "Silício", "atomicMass": 28.085, "category": "Semimetais", "group": 14, "period": 3, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Ne] 3s² 3p²", "shells": [2, 8, 4] },
    { "atomicNumber": 15, "symbol": "P", "namePt": "Fósforo", "atomicMass": 30.974, "category": "Não Metais", "group": 15, "period": 3, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Ne] 3s² 3p³", "shells": [2, 8, 5] },
    { "atomicNumber": 16, "symbol": "S", "namePt": "Enxofre", "atomicMass": 32.06, "category": "Não Metais", "group": 16, "period": 3, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Ne] 3s² 3p⁴", "shells": [2, 8, 6] },
    { "atomicNumber": 17, "symbol": "Cl", "namePt": "Cloro", "atomicMass": 35.45, "category": "Halogênios", "group": 17, "period": 3, "block": "p", "state": "Gasoso", "electronConfigurationShort": "[Ne] 3s² 3p⁵", "shells": [2, 8, 7] },
    { "atomicNumber": 18, "symbol": "Ar", "namePt": "Argônio", "atomicMass": 39.948, "category": "Gases Nobres", "group": 18, "period": 3, "block": "p", "state": "Gasoso", "electronConfigurationShort": "[Ne] 3s² 3p⁶", "shells": [2, 8, 8] },

    
    { "atomicNumber": 19, "symbol": "K", "namePt": "Potássio", "atomicMass": 39.098, "category": "Metais Alcalinos", "group": 1, "period": 4, "block": "s", "state": "Sólido", "electronConfigurationShort": "[Ar] 4s¹", "shells": [2, 8, 8, 1] },
    { "atomicNumber": 20, "symbol": "Ca", "namePt": "Cálcio", "atomicMass": 40.078, "category": "Metais Alcalino-Terrosos", "group": 2, "period": 4, "block": "s", "state": "Sólido", "electronConfigurationShort": "[Ar] 4s²", "shells": [2, 8, 8, 2] },
    { "atomicNumber": 21, "symbol": "Sc", "namePt": "Escândio", "atomicMass": 44.956, "category": "Metais de Transição", "group": 3, "period": 4, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d¹ 4s²", "shells": [2, 8, 9, 2] },
    { "atomicNumber": 22, "symbol": "Ti", "namePt": "Titânio", "atomicMass": 47.867, "category": "Metais de Transição", "group": 4, "period": 4, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d² 4s²", "shells": [2, 8, 10, 2] },
    { "atomicNumber": 23, "symbol": "V", "namePt": "Vanádio", "atomicMass": 50.942, "category": "Metais de Transição", "group": 5, "period": 4, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d³ 4s²", "shells": [2, 8, 11, 2] },
    { "atomicNumber": 24, "symbol": "Cr", "namePt": "Cromo", "atomicMass": 51.996, "category": "Metais de Transição", "group": 6, "period": 4, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d⁵ 4s¹", "shells": [2, 8, 13, 1] },
    { "atomicNumber": 25, "symbol": "Mn", "namePt": "Manganês", "atomicMass": 54.938, "category": "Metais de Transição", "group": 7, "period": 4, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d⁵ 4s²", "shells": [2, 8, 13, 2] },
    { "atomicNumber": 26, "symbol": "Fe", "namePt": "Ferro", "atomicMass": 55.845, "category": "Metais de Transição", "group": 8, "period": 4, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d⁶ 4s²", "shells": [2, 8, 14, 2] },
    { "atomicNumber": 27, "symbol": "Co", "namePt": "Cobalto", "atomicMass": 58.933, "category": "Metais de Transição", "group": 9, "period": 4, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d⁷ 4s²", "shells": [2, 8, 15, 2] },
    { "atomicNumber": 28, "symbol": "Ni", "namePt": "Níquel", "atomicMass": 58.693, "category": "Metais de Transição", "group": 10, "period": 4, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d⁸ 4s²", "shells": [2, 8, 16, 2] },
    { "atomicNumber": 29, "symbol": "Cu", "namePt": "Cobre", "atomicMass": 63.546, "category": "Metais de Transição", "group": 11, "period": 4, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d¹0 4s¹", "shells": [2, 8, 18, 1] },
    { "atomicNumber": 30, "symbol": "Zn", "namePt": "Zinco", "atomicMass": 65.38, "category": "Metais de Transição", "group": 12, "period": 4, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d¹0 4s²", "shells": [2, 8, 18, 2] },
    { "atomicNumber": 31, "symbol": "Ga", "namePt": "Gálio", "atomicMass": 69.723, "category": "Metais Pós-Transição", "group": 13, "period": 4, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d¹0 4s² 4p¹", "shells": [2, 8, 18, 3] },
    { "atomicNumber": 32, "symbol": "Ge", "namePt": "Germânio", "atomicMass": 72.630, "category": "Semimetais", "group": 14, "period": 4, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d¹0 4s² 4p²", "shells": [2, 8, 18, 4] },
    { "atomicNumber": 33, "symbol": "As", "namePt": "Arsênio", "atomicMass": 74.922, "category": "Semimetais", "group": 15, "period": 4, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d¹0 4s² 4p³", "shells": [2, 8, 18, 5] },
    { "atomicNumber": 34, "symbol": "Se", "namePt": "Selênio", "atomicMass": 78.971, "category": "Não Metais", "group": 16, "period": 4, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Ar] 3d¹0 4s² 4p⁴", "shells": [2, 8, 18, 6] },
    { "atomicNumber": 35, "symbol": "Br", "namePt": "Bromo", "atomicMass": 79.904, "category": "Halogênios", "group": 17, "period": 4, "block": "p", "state": "Líquido", "electronConfigurationShort": "[Ar] 3d¹0 4s² 4p⁵", "shells": [2, 8, 18, 7] },
    { "atomicNumber": 36, "symbol": "Kr", "namePt": "Criptônio", "atomicMass": 83.798, "category": "Gases Nobres", "group": 18, "period": 4, "block": "p", "state": "Gasoso", "electronConfigurationShort": "[Ar] 3d¹0 4s² 4p⁶", "shells": [2, 8, 18, 8] },

  
    { "atomicNumber": 37, "symbol": "Rb", "namePt": "Rubídio", "atomicMass": 85.468, "category": "Metais Alcalinos", "group": 1, "period": 5, "block": "s", "state": "Sólido", "electronConfigurationShort": "[Kr] 5s¹", "shells": [2, 8, 18, 8, 1] },
    { "atomicNumber": 38, "symbol": "Sr", "namePt": "Estrôncio", "atomicMass": 87.62, "category": "Metais Alcalino-Terrosos", "group": 2, "period": 5, "block": "s", "state": "Sólido", "electronConfigurationShort": "[Kr] 5s²", "shells": [2, 8, 18, 8, 2] },
    { "atomicNumber": 39, "symbol": "Y", "namePt": "Ítrio", "atomicMass": 88.906, "category": "Metais de Transição", "group": 3, "period": 5, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d¹ 5s²", "shells": [2, 8, 18, 9, 2] },
    { "atomicNumber": 40, "symbol": "Zr", "namePt": "Zircônio", "atomicMass": 91.224, "category": "Metais de Transição", "group": 4, "period": 5, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d² 5s²", "shells": [2, 8, 18, 10, 2] },
    { "atomicNumber": 41, "symbol": "Nb", "namePt": "Nióbio", "atomicMass": 92.906, "category": "Metais de Transição", "group": 5, "period": 5, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d⁴ 5s¹", "shells": [2, 8, 18, 12, 1] },
    { "atomicNumber": 42, "symbol": "Mo", "namePt": "Molibdênio", "atomicMass": 95.95, "category": "Metais de Transição", "group": 6, "period": 5, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d⁵ 5s¹", "shells": [2, 8, 18, 13, 1] },
    { "atomicNumber": 43, "symbol": "Tc", "namePt": "Tecnécio", "atomicMass": 98, "category": "Metais de Transição", "group": 7, "period": 5, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d⁵ 5s²", "shells": [2, 8, 18, 13, 2] },
    { "atomicNumber": 44, "symbol": "Ru", "namePt": "Rutênio", "atomicMass": 101.07, "category": "Metais de Transição", "group": 8, "period": 5, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d⁷ 5s¹", "shells": [2, 8, 18, 15, 1] },
    { "atomicNumber": 45, "symbol": "Rh", "namePt": "Ródio", "atomicMass": 102.91, "category": "Metais de Transição", "group": 9, "period": 5, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d⁸ 5s¹", "shells": [2, 8, 18, 16, 1] },
    { "atomicNumber": 46, "symbol": "Pd", "namePt": "Paládio", "atomicMass": 106.42, "category": "Metais de Transição", "group": 10, "period": 5, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d¹⁰", "shells": [2, 8, 18, 18] },
    { "atomicNumber": 47, "symbol": "Ag", "namePt": "Prata", "atomicMass": 107.868, "category": "Metais de Transição", "group": 11, "period": 5, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d¹⁰ 5s¹", "shells": [2, 8, 18, 18, 1] },
    { "atomicNumber": 48, "symbol": "Cd", "namePt": "Cádmio", "atomicMass": 112.414, "category": "Metais de Transição", "group": 12, "period": 5, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d¹⁰ 5s²", "shells": [2, 8, 18, 18, 2] },
    { "atomicNumber": 49, "symbol": "In", "namePt": "Índio", "atomicMass": 114.818, "category": "Metais Pós-Transição", "group": 13, "period": 5, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d¹⁰ 5s² 5p¹", "shells": [2, 8, 18, 18, 3] },
    { "atomicNumber": 50, "symbol": "Sn", "namePt": "Estanho", "atomicMass": 118.710, "category": "Metais Pós-Transição", "group": 14, "period": 5, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d¹⁰ 5s² 5p²", "shells": [2, 8, 18, 18, 4] },
    { "atomicNumber": 51, "symbol": "Sb", "namePt": "Antimônio", "atomicMass": 121.760, "category": "Semimetais", "group": 15, "period": 5, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d¹⁰ 5s² 5p³", "shells": [2, 8, 18, 18, 5] },
    { "atomicNumber": 52, "symbol": "Te", "namePt": "Telúrio", "atomicMass": 127.60, "category": "Semimetais", "group": 16, "period": 5, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d¹⁰ 5s² 5p⁴", "shells": [2, 8, 18, 18, 6] },
    { "atomicNumber": 53, "symbol": "I", "namePt": "Iodo", "atomicMass": 126.904, "category": "Halogênios", "group": 17, "period": 5, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Kr] 4d¹⁰ 5s² 5p⁵", "shells": [2, 8, 18, 18, 7] },
    { "atomicNumber": 54, "symbol": "Xe", "namePt": "Xênon", "atomicMass": 131.293, "category": "Gases Nobres", "group": 18, "period": 5, "block": "p", "state": "Gasoso", "electronConfigurationShort": "[Kr] 4d¹⁰ 5s² 5p⁶", "shells": [2, 8, 18, 18, 8] },

  
    { "atomicNumber": 55, "symbol": "Cs", "namePt": "Césio", "atomicMass": 132.905, "category": "Metais Alcalinos", "group": 1, "period": 6, "block": "s", "state": "Sólido", "electronConfigurationShort": "[Xe] 6s¹", "shells": [2, 8, 18, 18, 8, 1] },
    { "atomicNumber": 56, "symbol": "Ba", "namePt": "Bário", "atomicMass": 137.327, "category": "Metais Alcalino-Terrosos", "group": 2, "period": 6, "block": "s", "state": "Sólido", "electronConfigurationShort": "[Xe] 6s²", "shells": [2, 8, 18, 18, 8, 2] },
    
  
    { "atomicNumber": 57, "symbol": "La", "namePt": "Lantânio", "atomicMass": 138.905, "category": "Lantanídeos", "group": 3, "period": 6, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Xe] 5d¹ 6s²", "shells": [2, 8, 18, 18, 9, 2] },
    { "atomicNumber": 58, "symbol": "Ce", "namePt": "Cério", "atomicMass": 140.116, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹ 5d¹ 6s²", "shells": [2, 8, 18, 19, 9, 2] },
    { "atomicNumber": 59, "symbol": "Pr", "namePt": "Praseodímio", "atomicMass": 140.908, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f³ 6s²", "shells": [2, 8, 18, 21, 8, 2] },
    { "atomicNumber": 60, "symbol": "Nd", "namePt": "Neodímio", "atomicMass": 144.242, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f⁴ 6s²", "shells": [2, 8, 18, 22, 8, 2] },
    { "atomicNumber": 61, "symbol": "Pm", "namePt": "Promécio", "atomicMass": 145, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f⁵ 6s²", "shells": [2, 8, 18, 23, 8, 2] },
    { "atomicNumber": 62, "symbol": "Sm", "namePt": "Samário", "atomicMass": 150.36, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f⁶ 6s²", "shells": [2, 8, 18, 24, 8, 2] },
    { "atomicNumber": 63, "symbol": "Eu", "namePt": "Európio", "atomicMass": 151.964, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f⁷ 6s²", "shells": [2, 8, 18, 25, 8, 2] },
    { "atomicNumber": 64, "symbol": "Gd", "namePt": "Gadolínio", "atomicMass": 157.25, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f⁷ 5d¹ 6s²", "shells": [2, 8, 18, 25, 9, 2] },
    { "atomicNumber": 65, "symbol": "Tb", "namePt": "Térbio", "atomicMass": 158.925, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f⁹ 6s²", "shells": [2, 8, 18, 27, 8, 2] },
    { "atomicNumber": 66, "symbol": "Dy", "namePt": "Disprósio", "atomicMass": 162.500, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁰ 6s²", "shells": [2, 8, 18, 28, 8, 2] },
    { "atomicNumber": 67, "symbol": "Ho", "namePt": "Hólmio", "atomicMass": 164.930, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹¹ 6s²", "shells": [2, 8, 18, 29, 8, 2] },
    { "atomicNumber": 68, "symbol": "Er", "namePt": "Érbio", "atomicMass": 167.259, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹² 6s²", "shells": [2, 8, 18, 30, 8, 2] },
    { "atomicNumber": 69, "symbol": "Tm", "namePt": "Túlio", "atomicMass": 168.934, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹³ 6s²", "shells": [2, 8, 18, 31, 8, 2] },
    { "atomicNumber": 70, "symbol": "Yb", "namePt": "Itérbio", "atomicMass": 173.045, "category": "Lantanídeos", "group": 3, "period": 6, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 6s²", "shells": [2, 8, 18, 32, 8, 2] },
    { "atomicNumber": 71, "symbol": "Lu", "namePt": "Lutécio", "atomicMass": 174.967, "category": "Lantanídeos", "group": 3, "period": 6, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d¹ 6s²", "shells": [2, 8, 18, 32, 9, 2] },
    
  
    { "atomicNumber": 72, "symbol": "Hf", "namePt": "Háfnio", "atomicMass": 178.49, "category": "Metais de Transição", "group": 4, "period": 6, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d² 6s²", "shells": [2, 8, 18, 32, 10, 2] },
    { "atomicNumber": 73, "symbol": "Ta", "namePt": "Tântalo", "atomicMass": 180.948, "category": "Metais de Transição", "group": 5, "period": 6, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d³ 6s²", "shells": [2, 8, 18, 32, 11, 2] },
    { "atomicNumber": 74, "symbol": "W", "namePt": "Tungstênio", "atomicMass": 183.84, "category": "Metais de Transição", "group": 6, "period": 6, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d⁴ 6s²", "shells": [2, 8, 18, 32, 12, 2] },
    { "atomicNumber": 75, "symbol": "Re", "namePt": "Rênio", "atomicMass": 186.207, "category": "Metais de Transição", "group": 7, "period": 6, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d⁵ 6s²", "shells": [2, 8, 18, 32, 13, 2] },
    { "atomicNumber": 76, "symbol": "Os", "namePt": "Ósmio", "atomicMass": 190.23, "category": "Metais de Transição", "group": 8, "period": 6, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d⁶ 6s²", "shells": [2, 8, 18, 32, 14, 2] },
    { "atomicNumber": 77, "symbol": "Ir", "namePt": "Irídio", "atomicMass": 192.217, "category": "Metais de Transição", "group": 9, "period": 6, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d⁷ 6s²", "shells": [2, 8, 18, 32, 15, 2] },
    { "atomicNumber": 78, "symbol": "Pt", "namePt": "Platina", "atomicMass": 195.084, "category": "Metais de Transição", "group": 10, "period": 6, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d⁹ 6s¹", "shells": [2, 8, 18, 32, 17, 1] },
    { "atomicNumber": 79, "symbol": "Au", "namePt": "Ouro", "atomicMass": 196.967, "category": "Metais de Transição", "group": 11, "period": 6, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d¹0 6s¹", "shells": [2, 8, 18, 32, 18, 1] },
    { "atomicNumber": 80, "symbol": "Hg", "namePt": "Mercúrio", "atomicMass": 200.592, "category": "Metais de Transição", "group": 12, "period": 6, "block": "d", "state": "Líquido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d¹0 6s²", "shells": [2, 8, 18, 32, 18, 2] },
    { "atomicNumber": 81, "symbol": "Tl", "namePt": "Tálio", "atomicMass": 204.38, "category": "Metais Pós-Transição", "group": 13, "period": 6, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d¹0 6s² 6p¹", "shells": [2, 8, 18, 32, 18, 3] },
    { "atomicNumber": 82, "symbol": "Pb", "namePt": "Chumbo", "atomicMass": 207.2, "category": "Metais Pós-Transição", "group": 14, "period": 6, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d¹0 6s² 6p²", "shells": [2, 8, 18, 32, 18, 4] },
    { "atomicNumber": 83, "symbol": "Bi", "namePt": "Bismuto", "atomicMass": 208.980, "category": "Metais Pós-Transição", "group": 15, "period": 6, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d¹0 6s² 6p³", "shells": [2, 8, 18, 32, 18, 5] },
    { "atomicNumber": 84, "symbol": "Po", "namePt": "Polônio", "atomicMass": 209, "category": "Metais Pós-Transição", "group": 16, "period": 6, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d¹0 6s² 6p⁴", "shells": [2, 8, 18, 32, 18, 6] },
    { "atomicNumber": 85, "symbol": "At", "namePt": "Astato", "atomicMass": 210, "category": "Halogênios", "group": 17, "period": 6, "block": "p", "state": "Sólido", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d¹0 6s² 6p⁵", "shells": [2, 8, 18, 32, 18, 7] },
    { "atomicNumber": 86, "symbol": "Rn", "namePt": "Radônio", "atomicMass": 222, "category": "Gases Nobres", "group": 18, "period": 6, "block": "p", "state": "Gasoso", "electronConfigurationShort": "[Xe] 4f¹⁴ 5d¹0 6s² 6p⁶", "shells": [2, 8, 18, 32, 18, 8] },
    
 
    { "atomicNumber": 87, "symbol": "Fr", "namePt": "Frâncio", "atomicMass": 223, "category": "Metais Alcalinos", "group": 1, "period": 7, "block": "s", "state": "Sólido", "electronConfigurationShort": "[Rn] 7s¹", "shells": [2, 8, 18, 32, 18, 8, 1] },
    { "atomicNumber": 88, "symbol": "Ra", "namePt": "Rádio", "atomicMass": 226, "category": "Metais Alcalino-Terrosos", "group": 2, "period": 7, "block": "s", "state": "Sólido", "electronConfigurationShort": "[Rn] 7s²", "shells": [2, 8, 18, 32, 18, 8, 2] },

 
    { "atomicNumber": 89, "symbol": "Ac", "namePt": "Actínio", "atomicMass": 227, "category": "Actinídeos", "group": 3, "period": 7, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Rn] 6d¹ 7s²", "shells": [2, 8, 18, 32, 18, 9, 2] },
    { "atomicNumber": 90, "symbol": "Th", "namePt": "Tório", "atomicMass": 232.038, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 6d² 7s²", "shells": [2, 8, 18, 32, 18, 10, 2] },
    { "atomicNumber": 91, "symbol": "Pa", "namePt": "Protactínio", "atomicMass": 231.036, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f² 6d¹ 7s²", "shells": [2, 8, 18, 32, 20, 9, 2] },
    { "atomicNumber": 92, "symbol": "U", "namePt": "Urânio", "atomicMass": 238.029, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f³ 6d¹ 7s²", "shells": [2, 8, 18, 32, 21, 9, 2] },
    { "atomicNumber": 93, "symbol": "Np", "namePt": "Netúnio", "atomicMass": 237, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f⁴ 6d¹ 7s²", "shells": [2, 8, 18, 32, 22, 9, 2] },
    { "atomicNumber": 94, "symbol": "Pu", "namePt": "Plutônio", "atomicMass": 244, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f⁶ 7s²", "shells": [2, 8, 18, 32, 24, 8, 2] },
    { "atomicNumber": 95, "symbol": "Am", "namePt": "Amerício", "atomicMass": 243, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f⁷ 7s²", "shells": [2, 8, 18, 32, 25, 8, 2] },
    { "atomicNumber": 96, "symbol": "Cm", "namePt": "Cúrio", "atomicMass": 247, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f⁷ 6d¹ 7s²", "shells": [2, 8, 18, 32, 25, 9, 2] },
    { "atomicNumber": 97, "symbol": "Bk", "namePt": "Berquélio", "atomicMass": 247, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f⁹ 7s²", "shells": [2, 8, 18, 32, 27, 8, 2] },
    { "atomicNumber": 98, "symbol": "Cf", "namePt": "Califórnio", "atomicMass": 251, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹0 7s²", "shells": [2, 8, 18, 32, 28, 8, 2] },
    { "atomicNumber": 99, "symbol": "Es", "namePt": "Einstênio", "atomicMass": 252, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹¹ 7s²", "shells": [2, 8, 18, 32, 29, 8, 2] },
    { "atomicNumber": 100, "symbol": "Fm", "namePt": "Férmio", "atomicMass": 257, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹² 7s²", "shells": [2, 8, 18, 32, 30, 8, 2] },
    { "atomicNumber": 101, "symbol": "Md", "namePt": "Mendelévio", "atomicMass": 258, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹³ 7s²", "shells": [2, 8, 18, 32, 31, 8, 2] },
    { "atomicNumber": 102, "symbol": "No", "namePt": "Nobélio", "atomicMass": 259, "category": "Actinídeos", "group": 3, "period": 7, "block": "f", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹⁴ 7s²", "shells": [2, 8, 18, 32, 32, 8, 2] },
    { "atomicNumber": 103, "symbol": "Lr", "namePt": "Laurêncio", "atomicMass": 266, "category": "Actinídeos", "group": 3, "period": 7, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹⁴ 7s² 7p¹", "shells": [2, 8, 18, 32, 32, 8, 3] },

  
    { "atomicNumber": 104, "symbol": "Rf", "namePt": "Rutherfórdio", "atomicMass": 267, "category": "Metais de Transição", "group": 4, "period": 7, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d² 7s²", "shells": [2, 8, 18, 32, 32, 10, 2] },
    { "atomicNumber": 105, "symbol": "Db", "namePt": "Dúbnio", "atomicMass": 268, "category": "Metais de Transição", "group": 5, "period": 7, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d³ 7s²", "shells": [2, 8, 18, 32, 32, 11, 2] },
    { "atomicNumber": 106, "symbol": "Sg", "namePt": "Seabórgio", "atomicMass": 269, "category": "Metais de Transição", "group": 6, "period": 7, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d⁴ 7s²", "shells": [2, 8, 18, 32, 32, 12, 2] },
    { "atomicNumber": 107, "symbol": "Bh", "namePt": "Bóhrio", "atomicMass": 270, "category": "Metais de Transição", "group": 7, "period": 7, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d⁵ 7s²", "shells": [2, 8, 18, 32, 32, 13, 2] },
    { "atomicNumber": 108, "symbol": "Hs", "namePt": "Hássio", "atomicMass": 277, "category": "Metais de Transição", "group": 8, "period": 7, "block": "d", "state": "Sólido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d⁶ 7s²", "shells": [2, 8, 18, 32, 32, 14, 2] },
    { "atomicNumber": 109, "symbol": "Mt", "namePt": "Meitnério", "atomicMass": 278, "category": "Metais de Transição (Sintéticos)", "group": 9, "period": 7, "block": "d", "state": "Desconhecido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d⁷ 7s²", "shells": [2, 8, 18, 32, 32, 15, 2] },
    { "atomicNumber": 110, "symbol": "Ds", "namePt": "Darmstádio", "atomicMass": 281, "category": "Metais de Transição (Sintéticos)", "group": 10, "period": 7, "block": "d", "state": "Desconhecido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d⁸ 7s²", "shells": [2, 8, 18, 32, 32, 16, 2] },
    { "atomicNumber": 111, "symbol": "Rg", "namePt": "Roentgênio", "atomicMass": 282, "category": "Metais de Transição (Sintéticos)", "group": 11, "period": 7, "block": "d", "state": "Desconhecido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d⁹ 7s²", "shells": [2, 8, 18, 32, 32, 17, 2] },
    { "atomicNumber": 112, "symbol": "Cn", "namePt": "Copernício", "atomicMass": 285, "category": "Metais de Transição (Sintéticos)", "group": 12, "period": 7, "block": "d", "state": "Desconhecido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d¹0 7s²", "shells": [2, 8, 18, 32, 32, 18, 2] },
    { "atomicNumber": 113, "symbol": "Nh", "namePt": "Nihônio", "atomicMass": 286, "category": "Metais Pós-Transição", "group": 13, "period": 7, "block": "p", "state": "Desconhecido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d¹0 7s² 7p¹", "shells": [2, 8, 18, 32, 32, 18, 3] },
    { "atomicNumber": 114, "symbol": "Fl", "namePt": "Fleróvio", "atomicMass": 289, "category": "Metais Pós-Transição", "group": 14, "period": 7, "block": "p", "state": "Desconhecido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d¹0 7s² 7p²", "shells": [2, 8, 18, 32, 32, 18, 4] },
    { "atomicNumber": 115, "symbol": "Mc", "namePt": "Moscóvio", "atomicMass": 290, "category": "Metais Pós-Transição", "group": 15, "period": 7, "block": "p", "state": "Desconhecido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d¹0 7s² 7p³", "shells": [2, 8, 18, 32, 32, 18, 5] },
    { "atomicNumber": 116, "symbol": "Lv", "namePt": "Livermório", "atomicMass": 293, "category": "Metais Pós-Transição", "group": 16, "period": 7, "block": "p", "state": "Desconhecido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d¹0 7s² 7p⁴", "shells": [2, 8, 18, 32, 32, 18, 6] },
    { "atomicNumber": 117, "symbol": "Ts", "namePt": "Tenessino", "atomicMass": 294, "category": "Elementos Superpesados", "group": 17, "period": 7, "block": "p", "state": "Desconhecido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d¹0 7s² 7p⁵", "shells": [2, 8, 18, 32, 32, 18, 7] },
    { "atomicNumber": 118, "symbol": "Og", "namePt": "Oganessônio", "atomicMass": 294, "category": "Elementos Superpesados", "group": 18, "period": 7, "block": "p", "state": "Desconhecido", "electronConfigurationShort": "[Rn] 5f¹⁴ 6d¹0 7s² 7p⁶", "shells": [2, 8, 18, 32, 32, 18, 8] }
  ]
};